"""create_events_and_sessions_tables

Revision ID: 1d03365ca769
Revises: 1754ca114470
Create Date: 2026-05-31 01:31:07.930164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d03365ca769'
down_revision: Union[str, None] = '1754ca114470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brigade_transactions',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('offer_name', sa.String(), nullable=True),
    sa.Column('discount_code', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('order_time', sa.Time(), nullable=True),
    sa.Column('return_id', sa.String(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_number', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('dep_name', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('brand_type', sa.String(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('salesperson_id', sa.String(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('salesperson_name', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('gmv', sa.Float(), nullable=True),
    sa.Column('nmv', sa.Float(), nullable=True),
    sa.Column('coupon_amount', sa.Float(), nullable=True),
    sa.Column('item_promotion', sa.Float(), nullable=True),
    sa.Column('amt_without_gwp', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('pb_eb_sale', sa.String(), nullable=True),
    sa.Column('week_assigned', sa.String(), nullable=True),
    sa.Column('tax_m', sa.Float(), nullable=True),
    sa.Column('taxable_amt', sa.Float(), nullable=True),
    sa.Column('tax_amt', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'id')
    )
    op.create_index(op.f('ix_brigade_transactions_id'), 'brigade_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_brigade_transactions_invoice_number'), 'brigade_transactions', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_brigade_transactions_order_id'), 'brigade_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_brigade_transactions_salesperson_id'), 'brigade_transactions', ['salesperson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brigade_transactions_salesperson_id'), table_name='brigade_transactions')
    op.drop_index(op.f('ix_brigade_transactions_order_id'), table_name='brigade_transactions')
    op.drop_index(op.f('ix_brigade_transactions_invoice_number'), table_name='brigade_transactions')
    op.drop_index(op.f('ix_brigade_transactions_id'), table_name='brigade_transactions')
    op.drop_table('brigade_transactions')
    # ### end Alembic commands ###
