"""Initial migration

Revision ID: 353ab1f6ab55
Revises: 
Create Date: 2026-05-30 13:28:28.595749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '353ab1f6ab55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('visitor_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.Enum('ENTRY', 'EXIT', 'ZONE_ENTER', 'ZONE_EXIT', 'ZONE_DWELL', 'BILLING_QUEUE_JOIN', 'BILLING_QUEUE_ABANDON', 'REENTRY', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=True),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_event_id'), 'event', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_store_id'), 'event', ['store_id'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_visitor_id'), 'event', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_event_zone_id'), 'event', ['zone_id'], unique=False)
    op.create_table('visitor_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journey_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone_dwell_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone_transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('has_converted', sa.Boolean(), nullable=False),
    sa.Column('has_joined_billing_queue', sa.Boolean(), nullable=False),
    sa.Column('associated_txn_id', sa.String(length=100), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_visitor_session_associated_txn_id'), 'visitor_session', ['associated_txn_id'], unique=False)
    op.create_index(op.f('ix_visitor_session_entered_at'), 'visitor_session', ['entered_at'], unique=False)
    op.create_index(op.f('ix_visitor_session_session_id'), 'visitor_session', ['session_id'], unique=False)
    op.create_index(op.f('ix_visitor_session_store_id'), 'visitor_session', ['store_id'], unique=False)
    op.create_index(op.f('ix_visitor_session_visitor_id'), 'visitor_session', ['visitor_id'], unique=False)
    op.create_table('transaction',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['visitor_session.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_session_id'), 'transaction', ['session_id'], unique=False)
    op.create_index(op.f('ix_transaction_store_id'), 'transaction', ['store_id'], unique=False)
    op.create_index(op.f('ix_transaction_timestamp'), 'transaction', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_id'), 'transaction', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_timestamp'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_store_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_session_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_visitor_session_visitor_id'), table_name='visitor_session')
    op.drop_index(op.f('ix_visitor_session_store_id'), table_name='visitor_session')
    op.drop_index(op.f('ix_visitor_session_session_id'), table_name='visitor_session')
    op.drop_index(op.f('ix_visitor_session_entered_at'), table_name='visitor_session')
    op.drop_index(op.f('ix_visitor_session_associated_txn_id'), table_name='visitor_session')
    op.drop_table('visitor_session')
    op.drop_index(op.f('ix_event_zone_id'), table_name='event')
    op.drop_index(op.f('ix_event_visitor_id'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_store_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
