"""create_events_and_visitor_sessions_tables

Revision ID: c4e0cafcc895
Revises: 1d03365ca769
Create Date: 2026-05-31 01:43:04.290419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e0cafcc895'
down_revision: Union[str, None] = '1d03365ca769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
